### ISSUE TITLE
Deliverable Planning Meeting, Scheduled, Sunday, October 15, 6:30 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#21]
# Topics
- [x] Review Hazard Analysis rubrics.
- [x] Breakdown tasks.
- [x] Prepare questions for TA review session on Monday.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
# Tasks
- [ ] Close SRS peer review issues.
- [ ] SRS formatting: page numbers.
- [ ]
