### ISSUE TITLE
Deliverable Review Meeting, Scheduled, Sunday, September 24, 8:30 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#3]
# Topics
1. [x] Go over individual work on Problem Statement and Goals, Development Plan. Finalize the deliverable documentation.
2. [x] Follow up with research for WebRTC and ML models.
3. [x] Arrange meeting with Andrew for existing code demo.
4. [x] Assign work for next week.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
# Meeting decisions
## Break down of tasks until next meeting
### ML paper readings
- [ ] @yex33 [SMPL](https://smpl.is.tue.mpg.de)
- [ ] @qstommyshu  [OpenPose](https://arxiv.org/abs/1812.08008)
- [ ] @KehaoHuang [ShapeMask](https://arxiv.org/abs/1904.03239)
### Emails
- [ ] @qstommyshu Arrange a code demo session with Andrew.
- [ ] @qstommyshu Ask both supervisors about IP ownership and project licensing.
### Research and information gathering
- [ ] @qstommyshu, @KehaoHuang Different SRS templates. Pay attention to Meyer's. Make decision by September 25th for the team on which SRS template to follow for our project.
- [ ] @qstommyshu, @KehaoHuang Once the SRS template has been decided, continue to gather information for writing SRS following the decided template.
- [ ] @marischan888, @jiaoa3 Alternatives to WebRTC for real-time communication interface which would better suit our project needs. Make and report decision by September 25th.
- [ ] @marischan888, @jiaoa3 Continue to study the alternative interface and gain preliminary knowledge for implementations.
## Tasks due for the coming deliverable.
- [ ] @yex33 Problem Statement and Development plan formatting and submission.
