### ISSUE TITLE
Deliverable Planning Meeting, Scheduled, Wednesday, Nov 1, 7:30 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#33]
# Topics
- [x] Discuss plans for PoC.
- [x] Review work done for VnV.

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
# Tasks
- [ ] Review test cases owned and connect them to appropriate requirements.
