### ISSUE TITLE
Deliverable Review and Planning Meeting, Popup, Monday, September 25, 8:30 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#6]
# Topics
- [x] @yex33 Finalize on the content and formatting on Problem Statement & Dev Plan.
- [x] @KehaoHuang Report finding on SRS templates. Help settling on one template of choice.
- [x] @yex33 Report findings from Prof. Spencer about the concerns in project planning and implementations.
- [x] Plan work till next meeting

# Attendance (popup meeting, non-required)
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
# Decisions Made
1. Meyer's is the template of choice for SRS.
2. The scope of the project is flexible. POC demo does not need complete implementation. No need to worry and plan too far ahead. Trust the process and the documentations. Be transparent with the development progress.
3. Continue to work on the documents as if we are doing the whole project. We can always omit "extra" documentations if the scope needs to be changed later.
4. Following Andrew's architectural plan for the system explained on Teams, WebRTC will still be used for the project.
## Tasks
- [x] Review and merge document changes for deliverable 1.
- [ ] @marischan888, @jiaoa3 Continue to research on WebRTC topics, gain preliminary knowledge for implementations.
- [ ] Everyone read over the description of the Meyer's template. Go through each heading. Chip in ideas in [this Google Doc](https://docs.google.com/document/d/1H2GSj6eI4ijP67rO9DYVOC66j-r1Z9cpHPonfQtXaGk/edit?usp=sharing). Just words or sentences, no need to care about grammar.
## Other notes
- Reminder for @qstommyshu to check off the email tasks in [the previous meeting issue](https://github.com/InfiniView-AI/MotionMingle/issues/3#issuecomment-1732987742) once they're done.
- Also reminder in general for everybody to check off tasks in closed meeting issues. Maybe all these tasks should be converted to separate issues and put into the assignee's project board?
