### ISSUE TITLE
Deliverable Planning Meeting, Friday, Jan 5, 1:00 pm, Discord

### ISSUE THREAD

**Issue by qstommyshu** [InfiniView-AI/MotionMingle#63]
# Topics
- [x] Design Doc: System design tasks assignment

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by qstommyshu** [comment]
# Tasks (done by Jan 7 6:00 PM)
 - [ ] Figure out the requirements of *Connection Between Requirements and Design* section @yex33 @marischan888 @KehaoHuang 
 - [ ] Project Overview section @yex33 @marischan888 @KehaoHuang 
 - [ ] Other sections(except Timeline, Reference materials) @jiaoa3 @qstommyshu 
 - [ ] Reflections for System Design. @qstommyshu @yex33 @marischan888 @jiaoa3 @KehaoHuang
