### ISSUE TITLE
Deliverable Planning Meeting, Sunday, Jan 7, 6:00 pm, Discord

### ISSUE THREAD

**Issue by KehaoHuang** [InfiniView-AI/MotionMingle#64]
# Topics
- [x] Design Doc: System design review
- [x] Design Doc: SoftArchitacture tasks assignment

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by KehaoHuang** [comment]
# Tasks (done by Jan 10 6:00 PM)
 - [ ] Ask TA: STUN server is used by our system, should we include it as a module in the component diagram?
 - [ ] Ask TA: Does each module represent a class in the actual implementation?
 - [ ] Ask TA: Camera module?
 - [ ] Ask TA: Design decision?
 - [ ] Section 3 Intro, 4 Anticipated and unlikely changes: @qstommyshu
 - [ ] Section 5 Module Hierarchy, 6 Connection between Req and Design, 8 Traceability Matrix: @yex33 @marischan888
 - [ ] Section 7 Module Decomposition, 9 Use Hierarchy Between Modules: @KehaoHuang @jiaoa3
