### ISSUE TITLE
Deliverable Review and Planning Meeting, Wednesday, Jan 10, 6:00 pm, Discord

### ISSUE THREAD

**Issue by yex33** [InfiniView-AI/MotionMingle#65]
# Topics
- [x] Design Doc: MIS tasks assignment

# Attendance
- [x] @qstommyshu 
- [x] @yex33 
- [x] @marischan888 
- [x] @jiaoa3 
- [x] @KehaoHuang

**Comment by yex33** [comment]
## Notes
```
Intro, Notation, Module Decomposition -> server
M1: Hardware Hiding Modules -> ask in discussion
M2: User Authentication Module -> UI
M3: Instructor View Module -> UI
M4: Practitioner View Module -> UI
M5: Annotation Configuration Module -> server
M6: Network Monitoring Module -> UI
M7: Frontend Controller Module -> UI
M8: Video Transform Module -> server
M9: Skeleton Annotation Module -> server
// 可能得加一个annotation module
M10: Center of Mass Annotation Module -> server
M11: SFU Server Module  -> server
M12: STUN Server Module -> implemented by third party
```
- Commit .tex documents to GitHub
- Thread worker module, threads for types of annotation
- Revision history, acronyms, grammar.
## Tasks: done by Jan. 15
- [ ] UI @qstommyshu @KehaoHuang 
- [ ] server @yex33 @jiaoa3 @marischan888 
- [ ] By Jan. 16: 3 guys look at MIS with rubric, 2 guys MG, glance at system design 
- [ ] By Jan. 17: supervisor demo
